"""Report export and Mermaid parsing helpers for BA Assistant."""

from __future__ import annotations

import re
from datetime import datetime
from typing import List

from fpdf import FPDF
from fpdf.enums import XPos, YPos


MERMAID_START_TOKENS = (
    "flowchart",
    "graph",
    "sequenceDiagram",
    "classDiagram",
    "stateDiagram",
    "stateDiagram-v2",
    "erDiagram",
    "journey",
    "gantt",
    "pie",
    "mindmap",
    "timeline",
    "quadrantChart",
    "requirementDiagram",
)


def sanitize_pdf_text(text: str) -> str:
    # Strip all non-latin-1 characters (handle emojis, special Unicode, etc.)
    text = text.encode("latin-1", "replace").decode("latin-1")
    # Break very long unbroken strings (URLs, code, etc.) that fpdf can't wrap.
    max_chunk = 120
    words = text.split(" ")
    result = []
    for word in words:
        while len(word) > max_chunk:
            result.append(word[:max_chunk])
            word = word[max_chunk:]
        result.append(word)
    return " ".join(result)


def _safe_write_line(pdf: FPDF, text: str, h: int = 5) -> None:
    """Write a line to PDF, falling back to truncated version if it won't fit."""
    try:
        pdf.multi_cell(0, h, text)
    except Exception:
        try:
            safe = text[:120].encode("ascii", "replace").decode("ascii") + "..."
            pdf.multi_cell(0, h, safe)
        except Exception:
            try:
                pdf.cell(0, h, "[line skipped]")
            except Exception:
                pass


def markdown_to_pdf_lines(markdown: str) -> List[str]:
    lines: List[str] = []
    in_mermaid = False
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("```mermaid"):
            in_mermaid = True
            lines.append(
                "[Mermaid diagram code starts below. Open the Markdown version to view interactive diagrams.]"
            )
            continue
        if stripped == "```" and in_mermaid:
            in_mermaid = False
            continue
        if stripped.startswith("|---") or stripped.startswith("| --"):
            continue
        clean = re.sub(r"^#{1,6}\s+", "", line)
        clean = clean.replace("**", "").replace("__", "").replace("`", "")
        lines.append(clean)
    return lines


def generate_pdf(project_name: str, result_markdown: str) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    title = sanitize_pdf_text(f"BA Report: {project_name or 'Untitled Project'}")
    pdf.set_font("Helvetica", "B", 18)
    pdf.multi_cell(0, 10, title, align="C")
    pdf.ln(3)

    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(
        0,
        6,
        sanitize_pdf_text(
            f"Generated by BA Assistant | {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        ),
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
        align="C",
    )
    pdf.cell(0, 6, "touseefshaik.com", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
    pdf.ln(8)

    pdf.set_font("Helvetica", size=10)
    for line in markdown_to_pdf_lines(result_markdown):
        clean = sanitize_pdf_text(line)
        if not clean.strip():
            pdf.ln(2)
            continue
        if len(clean) < 90 and re.match(r"^\d{1,2}\.\s+|^[A-Z][A-Za-z /&,-]+$", clean.strip()):
            pdf.set_font("Helvetica", "B", 11)
            _safe_write_line(pdf, clean, h=6)
            pdf.set_font("Helvetica", size=10)
        else:
            _safe_write_line(pdf, clean, h=5)

    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(
        0,
        6,
        "Built by Touseef Shaik · touseefshaik.com",
        new_x=XPos.LMARGIN,
        new_y=YPos.NEXT,
        align="C",
    )

    raw = pdf.output()
    if isinstance(raw, bytes):
        return raw
    if isinstance(raw, bytearray):
        return bytes(raw)
    return raw.encode("latin-1", "replace")


def sanitize_mermaid_code(code: str) -> str:
    """Fix common LLM-generated Mermaid syntax errors."""
    lines = []
    for line in code.strip().splitlines():
        stripped = line.strip()
        if not stripped:
            lines.append("")
            continue
        stripped = re.sub(
            r'\[([^\]"]*?[()\'"<>&#;{}|?*+\[\]\/\\][^\]"]*?)\]',
            lambda match: f'["{match.group(1).replace(chr(34), chr(39))}"]',
            stripped,
        )
        stripped = re.sub(
            r'-->\|([^|]*?[()\'"<>&#;{}?*+\[\]\/\\][^|]*?)\|',
            lambda match: f'-->|"{match.group(1)}"|',
            stripped,
        )
        stripped = re.sub(
            r'-->\s*"([^"]*?)"',
            lambda match: f'--> "{match.group(1).replace(chr(39), "")}"',
            stripped,
        )
        lines.append(stripped)
    return "\n".join(lines)


def extract_mermaid_code(text: str) -> str:
    fenced = re.search(r"```mermaid\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    candidate = fenced.group(1).strip() if fenced else ""

    if not candidate:
        for token in MERMAID_START_TOKENS:
            pattern = rf"(?is)\b({re.escape(token)}\b.*?)(?:\n\n|$)"
            found = re.search(pattern, text)
            if found:
                candidate = found.group(1).strip()
                break

    candidate = sanitize_mermaid_code(candidate)

    if is_valid_mermaid(candidate):
        return candidate

    return """flowchart TD
    A[Raw Requirements] --> B[BA Analysis]
    B --> C[User Stories]
    B --> D[Architecture & Integrations]
    B --> E[Risk, Compliance & QA]
    C --> F[Prioritized Delivery Backlog]
    D --> F
    E --> F
    F --> G[Implementation Recommendation]"""


def is_valid_mermaid(code: str) -> bool:
    if not code or len(code) < 10:
        return False
    first_line = code.strip().splitlines()[0].strip()
    return first_line.startswith(MERMAID_START_TOKENS)
